name: Gitpod
on:
  push:
    paths:
      - 'example/gitpod/**'

jobs:
  gitpod:
    runs-on: ubuntu-latest
    name: Build Gitpod app
    steps:
      - name: checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.PUBLIC_DOCKER_USERNAME }}
          password: ${{ secrets.PUBLIC_DOCKER_PASSWORD }}
        # always uses a single image ,the changes are overridden
        # to-do versioning of the builds in case required
      - name: build configurator
        uses: docker/build-push-action@v2
        with:
          tags: razorpay/devstack:gitpod-${{ github.sha }}
          push: true
          file: ./example/gitpod/Dockerfile

  spinnaker:
    runs-on: self-hosted
    name: Spinnaker deploy
    steps:
      - name: deploy
        run: |
          echo 'Calling spinnaker deploy'
          curl -X POST -H "Content-Type: application/json \
          -d '{ "commit_id" : gitpod-${{ github.sha }}  }' \
          https://deploy-github-actions.razorpay.com/webhooks/webhook/gitpod-pid
          exit 1